### model
model_name_or_path: openai/gpt-oss-20b
#image_max_pixels: 262144
#video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full # lora / full
#lora_target: all
#lora_rank: 16
#lora_alpha: 32
#lora_dropout: 0.05
# freeze_vision_tower: true
# freeze_multi_modal_projector: true
# freeze_language_model: false
deepspeed: train/train_config/ds_z3_config.json
flash_attn: disabled
# attn_implementation: sdpa

### dataset
dataset_dir: DataPrepare/SFT_data/SFT_data/TDC_SFT_data_binary_Scaffold_wo_herg-c_ToxCast_butkiewicz  # SFT_data/SFT_data for TDC
dataset: TDC_SFT_data_scaffold_wo_herg-c_ToxCast_butkiewicz  # TDC_SFT_data_all_tasks for TDC // ChemCoT_SFT_data_all_tasks for ChemCoT
template: gpt_oss  # TODO: change model name
cutoff_len: 24570
tokenized_path: DataPrepare/SFT_data/SFT_data/TDC_SFT_data_binary_Scaffold_wo_herg-c_ToxCast_butkiewicz/tokenzied-gpt-oss-20b  # TODO: change model name
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 8
# Reasoning: low

### output
output_dir: checkpoints/gpt-oss-20b/full/sft-wo-herg-c_ToxCast_butkiewicz-TDC-binary-scaffold  # TODO: change model name
logging_steps: 100
save_strategy: epoch
# save_steps: 1500000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: gpt-oss-20b_full_sft_TDC_scaffold_wo_herg-c_ToxCast_butkiewicz_binary  # TODO: change model name
include_effective_tokens_per_second: true

### train
per_device_train_batch_size: 1 # TODO: fit model size
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

# tensor_model_parallel_size: 8
# sequence_parallel: false
# pipeline_model_parallel_size: 1
# bias_activation_fusion: true
# apply_rope_fusion: true
# use_distributed_optimizer: true
# overlap_param_gather: true
# overlap_grad_reduce: true
# moe_grouped_gemm: true
# moe_token_dispatcher_type: alltoall
# expert_model_parallel_size: 8
# recompute_granularity: full

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500[
